# -*- coding: utf-8 -*-
"""
v17.1.14 popup_assistant 함수 교체 패치 스크립트
UTF-8 인코딩 유지, popup_assistant 함수 전체 교체
"""

INPUT_FILE  = "sage_popups_v17_1_14.py"
OUTPUT_FILE = "sage_popups_v17_1_14.py"

NEW_FUNC = (
    '@st.dialog("🤖 어시스턴트", width="large")\n'
    'def popup_assistant():\n'
    '    """클로드 스타일 심플 채팅 UI v17.1.14"""\n'
    '\n'
    '    # ── 모델 목록 ──────────────────────────────────────────────\n'
    '    _MODELS = [\n'
    '        "gemma4:e2b",\n'
    '        "gemma4:e4b",\n'
    '        "gemini-2.5-flash",\n'
    '        "gemini-3.1-flash-lite",\n'
    '        "gemini-3.1-pro",\n'
    '        "tavily-search",\n'
    '    ]\n'
    '\n'
    '    # ── 세션 초기화 ────────────────────────────────────────────\n'
    '    _defs = {\n'
    '        "popup_selected_model": OLLAMA_MODEL,\n'
    '        "popup_history": [],\n'
    '        "popup_search_history": [],\n'
    '        "tavily_rag_context": "",\n'
    '        "sidebar_open": True,\n'
    '        "sidebar_tab": "",\n'
    '    }\n'
    '    for _k, _v in _defs.items():\n'
    '        if _k not in st.session_state:\n'
    '            st.session_state[_k] = _v\n'
    '\n'
    '    # ── 대화 영속성 복원 ───────────────────────────────────────\n'
    '    if not st.session_state.popup_history:\n'
    '        _loaded = _load_chat_history()\n'
    '        if _loaded:\n'
    '            st.session_state.popup_history = _loaded\n'
    '\n'
    '    current_part_key = _get_current_part()\n'
    '    current_part_info = PART_CONTEXT_MAP.get(current_part_key, PART_CONTEXT_MAP["part1"])\n'
    '    current_part_name = current_part_info["name"]\n'
    '\n'
    '    # ── 좌측 바 너비 (접기/펼치기) ────────────────────────────\n'
    '    _is_open = st.session_state.sidebar_open\n'
    '    _col_w = [1, 3] if _is_open else [0, 4]\n'
    '    col_left, col_chat = st.columns(_col_w, gap="small")\n'
    '\n'
    '    # ══════════════════════════════════════════\n'
    '    # 좌측 바\n'
    '    # ══════════════════════════════════════════\n'
    '    with col_left:\n'
    '        if _is_open:\n'
    '            # 접기 버튼\n'
    '            if st.button("≪", key="sb_close", help="좌측 바 접기"):\n'
    '                st.session_state.sidebar_open = False\n'
    '                st.rerun()\n'
    '\n'
    '            st.divider()\n'
    '\n'
    '            # 파트 표시\n'
    '            st.markdown(\n'
    '                f"<div style=\'background:#1a3a5c;color:#d4af6a;"\n'
    '                f"padding:6px 8px;border-radius:8px;"\n'
    '                f"font-size:0.78rem;font-weight:700;text-align:center;\'>"\n'
    '                f"📍 {current_part_name[:20]}</div>",\n'
    '                unsafe_allow_html=True,\n'
    '            )\n'
    '\n'
    '            st.divider()\n'
    '\n'
    '            # 기능 버튼\n'
    '            if st.button("💾 저장", use_container_width=True, key="sb_save"):\n'
    '                if st.session_state.popup_history:\n'
    '                    _save_to_obsidian_with_tags(\n'
    '                        content="\\n".join([\n'
    '                            f"[{m[\'role\'].upper()}] {m[\'content\']}"\n'
    '                            for m in st.session_state.popup_history\n'
    '                        ]),\n'
    '                        title=f"[Chat] {current_part_name}",\n'
    '                        source_type="Sage 팝업 대화",\n'
    '                        part_key=current_part_key,\n'
    '                        model_name=st.session_state.popup_selected_model,\n'
    '                    )\n'
    '                    st.toast("💾 저장 완료!")\n'
    '\n'
    '            if st.button("🔎 리서치", use_container_width=True, key="sb_res"):\n'
    '                st.session_state.sidebar_tab = (\n'
    '                    "" if st.session_state.sidebar_tab == "research" else "research"\n'
    '                )\n'
    '\n'
    '            if st.button("📂 파일", use_container_width=True, key="sb_file"):\n'
    '                st.session_state.sidebar_tab = (\n'
    '                    "" if st.session_state.sidebar_tab == "upload" else "upload"\n'
    '                )\n'
    '\n'
    '            if st.button("🧠 옵시디언", use_container_width=True, key="sb_obs"):\n'
    '                st.session_state.sidebar_tab = (\n'
    '                    "" if st.session_state.sidebar_tab == "obsidian" else "obsidian"\n'
    '                )\n'
    '\n'
    '            # 사이드 탭 영역\n'
    '            _tab = st.session_state.sidebar_tab\n'
    '            if _tab == "research":\n'
    '                st.divider()\n'
    '                st.caption("🔎 자료 조사")\n'
    '                _q = st.text_input("검색어", key="sb_q", label_visibility="collapsed",\n'
    '                                   placeholder="검색어 입력...")\n'
    '                if st.button("검색", key="sb_search_go") and _q:\n'
    '                    with st.spinner("검색 중..."):\n'
    '                        _tkey = st.session_state.get("tavily_api_key", "")\n'
    '                        _res = tavily_search(_q, _tkey)\n'
    '                        if "results" in _res:\n'
    '                            _ctx = "\\n".join([\n'
    '                                f"- {r.get(\'title\',\'\')}: {r.get(\'content\',\'\')[:200]}"\n'
    '                                for r in _res["results"][:3]\n'
    '                            ])\n'
    '                            st.session_state.tavily_rag_context = _ctx\n'
    '                            st.session_state.popup_search_history.append(\n'
    '                                {"query": _q, "context": _ctx}\n'
    '                            )\n'
    '                            st.success("✅ 수집 완료")\n'
    '\n'
    '            elif _tab == "upload":\n'
    '                st.divider()\n'
    '                st.caption("📂 파일 업로드")\n'
    '                _uf = st.file_uploader(\n'
    '                    "파일", type=["txt", "md", "pdf", "docx"],\n'
    '                    key="sb_uploader", label_visibility="collapsed"\n'
    '                )\n'
    '                if _uf and st.button("분석·저장", key="sb_analyze"):\n'
    '                    with st.spinner("분석 중..."):\n'
    '                        _text, _ = _read_uploaded_file_text(_uf)\n'
    '                        if _text:\n'
    '                            _save_to_obsidian_with_tags(\n'
    '                                content=_text[:5000],\n'
    '                                title=f"[업로드] {_uf.name}",\n'
    '                                source_type=f"파일 업로드 — {_uf.name}",\n'
    '                                part_key=current_part_key,\n'
    '                                model_name=st.session_state.popup_selected_model,\n'
    '                            )\n'
    '                            st.success("✅ 저장 완료")\n'
    '\n'
    '            elif _tab == "obsidian":\n'
    '                st.divider()\n'
    '                st.caption("🧠 최근 저장")\n'
    '                _vault = st.session_state.get("path_obsidian", "")\n'
    '                if _vault:\n'
    '                    try:\n'
    '                        from pathlib import Path as _P\n'
    '                        _recent = sorted(\n'
    '                            _P(_vault).rglob("*.md"),\n'
    '                            key=lambda f: f.stat().st_mtime,\n'
    '                            reverse=True\n'
    '                        )[:5]\n'
    '                        for _f in _recent:\n'
    '                            st.caption(f"📄 {_f.name[:25]}")\n'
    '                    except Exception:\n'
    '                        st.caption("자료 없음")\n'
    '                else:\n'
    '                    st.caption("경로 미설정")\n'
    '\n'
    '    # ══════════════════════════════════════════\n'
    '    # 대화창 (우측)\n'
    '    # ══════════════════════════════════════════\n'
    '    with col_chat:\n'
    '\n'
    '        # 펼치기 버튼 (좌측 바 닫혔을 때)\n'
    '        if not _is_open:\n'
    '            if st.button("≫", key="sb_open", help="좌측 바 열기"):\n'
    '                st.session_state.sidebar_open = True\n'
    '                st.rerun()\n'
    '\n'
    '        # 대화 기록\n'
    '        _chat_box = st.container(height=400)\n'
    '        with _chat_box:\n'
    '            if not st.session_state.popup_history:\n'
    '                st.markdown(\n'
    '                    "<div style=\'color:#555;text-align:center;margin-top:100px;"\n'
    '                    "font-size:0.95rem;\'>현자에게 무엇이든 물어보세요 🤖</div>",\n'
    '                    unsafe_allow_html=True,\n'
    '                )\n'
    '            for _idx, _msg in enumerate(st.session_state.popup_history):\n'
    '                with st.chat_message(_msg["role"]):\n'
    '                    st.markdown(_msg["content"])\n'
    '                    # 복사 버튼 (어시스턴트 응답만)\n'
    '                    if _msg["role"] == "assistant":\n'
    '                        _copy_id = f"copy_btn_{_idx}"\n'
    '                        if st.button("□ 복사", key=_copy_id, help="클립보드 복사"):\n'
    '                            st.code(_msg["content"], language="markdown")\n'
    '\n'
    '        # ── 입력 영역 (Claude 스타일) ──────────────────────────\n'
    '        # 모델 선택 (입력창 위 우측 정렬)\n'
    '        _, _mc = st.columns([3, 1])\n'
    '        with _mc:\n'
    '            _sel = st.selectbox(\n'
    '                "모델",\n'
    '                _MODELS,\n'
    '                index=_MODELS.index(st.session_state.popup_selected_model)\n'
    '                if st.session_state.popup_selected_model in _MODELS else 0,\n'
    '                key="popup_model_sel_14",\n'
    '                label_visibility="collapsed",\n'
    '            )\n'
    '            st.session_state.popup_selected_model = _sel\n'
    '\n'
    '        # 입력창 + 전송 버튼\n'
    '        _ic, _bc = st.columns([5, 1])\n'
    '        with _ic:\n'
    '            _prompt = st.text_input(\n'
    '                "",\n'
    '                key="popup_input_14",\n'
    '                placeholder="현자에게 물어보세요...",\n'
    '                label_visibility="collapsed",\n'
    '            )\n'
    '        with _bc:\n'
    '            _send = st.button("↑", key="popup_send_14", type="primary",\n'
    '                              use_container_width=True)\n'
    '\n'
    '        # ── 젬마 응답 처리 ─────────────────────────────────────\n'
    '        if _send and _prompt and _prompt.strip():\n'
    '            _cur_model = st.session_state.popup_selected_model\n'
    '\n'
    '            st.session_state.popup_history.append({\n'
    '                "role": "user",\n'
    '                "content": _prompt,\n'
    '                "model": _cur_model,\n'
    '                "part": current_part_name,\n'
    '            })\n'
    '\n'
    '            # 시스템 프롬프트 (초경량)\n'
    '            _sys = "너는 현자의 거울 스튜디오의 어시스턴트다. 묻는 말에 정확하고 짧게 답하라."\n'
    '            if st.session_state.get("tavily_rag_context"):\n'
    '                _sys += f"\\n\\n[참조 자료]\\n{st.session_state.tavily_rag_context[:800]}"\n'
    '\n'
    '            # 모델별 분기 처리\n'
    '            with st.spinner("● ● ●"):\n'
    '                import time as _time\n'
    '                _t0 = _time.perf_counter()\n'
    '\n'
    '                try:\n'
    '                    if _cur_model.startswith("gemma"):\n'
    '                        # 로컬 젬마 — 동기 방식\n'
    '                        _resp = call_gemma(_prompt, system=_sys, model=_cur_model)\n'
    '\n'
    '                    elif _cur_model == "tavily-search":\n'
    '                        # Tavily 웹 검색\n'
    '                        _tkey = st.session_state.get("tavily_api_key", "")\n'
    '                        _tres = tavily_search(_prompt, _tkey)\n'
    '                        if "results" in _tres:\n'
    '                            _ctx = "\\n\\n".join([\n'
    '                                f"**{r.get(\'title\',\'\')}**\\n{r.get(\'content\',\'\')[:300]}"\n'
    '                                for r in _tres["results"][:3]\n'
    '                            ])\n'
    '                            _resp = f"🌐 웹 검색 결과:\\n\\n{_ctx}"\n'
    '                            st.session_state.tavily_rag_context = _ctx\n'
    '                        else:\n'
    '                            _resp = "검색 결과가 없습니다."\n'
    '\n'
    '                    elif _cur_model.startswith("gemini"):\n'
    '                        # Gemini API\n'
    '                        try:\n'
    '                            import google.generativeai as _genai\n'
    '                            _genai.configure(\n'
    '                                api_key=st.session_state.get("gemini_api_key", "")\n'
    '                            )\n'
    '                            _gmodel = _genai.GenerativeModel(_cur_model)\n'
    '                            _gresp = _gmodel.generate_content(\n'
    '                                f"{_sys}\\n\\n{_prompt}"\n'
    '                            )\n'
    '                            _resp = _gresp.text\n'
    '                        except Exception as _ge:\n'
    '                            _resp = f"[Gemini 오류] {_ge}\\n→ API 키를 사이드바에서 확인하세요."\n'
    '                    else:\n'
    '                        _resp = call_gemma(_prompt, system=_sys, model=_cur_model)\n'
    '\n'
    '                except Exception as _e:\n'
    '                    _resp = f"[오류] {_e}"\n'
    '\n'
    '                _elapsed = _time.perf_counter() - _t0\n'
    '\n'
    '            # 응답 저장 및 표시\n'
    '            st.session_state.popup_history.append({\n'
    '                "role": "assistant",\n'
    '                "content": _resp,\n'
    '                "model": _cur_model,\n'
    '                "part": current_part_name,\n'
    '            })\n'
    '            _save_chat_history(st.session_state.popup_history)\n'
    '            st.rerun()\n'
)

# ── 파일 읽기 ──────────────────────────────────────────────
with open(INPUT_FILE, "r", encoding="utf-8") as f:
    content = f.read()

import sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
print(f"원본 파일 크기: {len(content)} bytes, 라인 수: {content.count(chr(10))+1}")

# ── popup_assistant 시작 마커 탐색 ────────────────────────
# v17.1.13에서 교체된 마커
start_marker_v13 = '@st.dialog("🤖 세이지 — Sage Mirror 어시스턴트", width="large")\ndef popup_assistant():'
# 원본 v17.1.12 마커 (혹시 대비)
start_marker_v12 = '@st.dialog("🤖 세이지 팝업 — Gemma × Tavily × Obsidian RAG", width="large")\ndef popup_assistant():'

start_idx = content.find(start_marker_v13)
if start_idx == -1:
    start_idx = content.find(start_marker_v12)
    if start_idx == -1:
        print("ERROR: popup_assistant 시작 마커를 찾지 못했습니다!")
        exit(1)
    print(f"v12 마커로 탐색 성공")
else:
    print(f"v13 마커로 탐색 성공")

start_line = content[:start_idx].count('\n') + 1
print(f"함수 시작 라인: {start_line}")

# ── 함수 끝 탐색 ──────────────────────────────────────────
# popup_assistant 다음에 오는 최상위 def/class 탐색
lines = content[start_idx:].split('\n')
func_end_line_offset = len(lines)  # 기본: 파일 끝

for i, line in enumerate(lines):
    if i < 2:  # 데코레이터 + def 라인 건너뜀
        continue
    # 최상위 레벨 def, class, @ 발견 시 종료
    stripped = line.rstrip()
    if stripped and not stripped[0].isspace():
        if (stripped.startswith('def ') or
            stripped.startswith('class ') or
            stripped.startswith('@')):
            func_end_line_offset = i
            print(f"다음 최상위 정의 발견 (오프셋 {i}): {stripped[:60]}")
            break

end_idx = start_idx + len('\n'.join(lines[:func_end_line_offset]))
print(f"교체 범위: {start_idx} ~ {end_idx} ({end_idx - start_idx} bytes)")

# ── 교체 ──────────────────────────────────────────────────
new_content = content[:start_idx] + NEW_FUNC + content[end_idx:]
print(f"새 파일 크기: {len(new_content)} bytes, 라인 수: {new_content.count(chr(10))+1}")

# ── 저장 (UTF-8) ──────────────────────────────────────────
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(new_content)

print(f"저장 완료: {OUTPUT_FILE}")
